const CONSTANTS = {
  THEMES:{
    LIGHT:'LIGHT',
    DARK:'DARK'
  },
  CHAT_ACTIONS:{
    DATA_RESPONSE_SUCCESS: "DATA_RESPONSE_SUCCESS",
    DATA_RESPONSE_ERROR: "DATA_RESPONSE_ERROR"
  },
  MENU_ACTIONS:{
    MENU_OPEN:"MENU_OPEN",
    MENU_CLOSE: "MENU_CLOSE"
  }
}
export default CONSTANTS;